    <?=
    loadComponent("head");
    loadComponent("navbar");
    loadComponent("showcase-search");
    loadComponent("top-banner");
    loadComponent("job-listings",["listings"=>$listings]);
    loadComponent("bottom-banner");
    loadComponent("tail");
    ?>